### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by patrickguevara** [mmieluch/laravel-vfs-provider#4]
With Laravel 5.4 out and little to no effect on this package's compatibility, I suggest changing the `composer.json` from...

```
"illuminate/support": "5.0.*|5.1.*|5.2.*|5.3.*",
"illuminate/filesystem": "5.0.*|5.1.*|5.2.*|5.3.*",
```

to...

```
"illuminate/support": "5.4.*",
"illuminate/filesystem": "5.4.*",
```

and tagging this version `v0.0.4`. 

If anyone needs 5.0-5.3 compatibility, they can use the `v0.0.3` release without issue.

**Comment by mmieluch** [comment]
Hi Patrick,

Firstly - huge thank you for the PR.

Secondly - I'd rather do the following:

- define the dependencies for the `illuminate`-type packages to `^5.0` which should work just fine for all 5.0-5.4 versions;
- tag it as 1.0.0, since it's stable (because there's nothing to break here :) The package would then become fully _semver_ compatible.

I think this approach would potentially create fewer issues for people who use older versions of `illuminate` packages (and 5.1 is LTS, so I have to keep that in mind).

I have a branch ready for merging, let me know by tomorrow.

**Comment by patrickguevara** [comment]
Even better! With what you're proposing you'd be able to sync major version numbers with the https://github.com/thephpleague/flysystem-vfs package (which has been as `1.0.2` for over a year).

I *honestly* forget there's an LTS that still needs supporting 😬

**Comment by mmieluch** [comment]
Great! In that case - I already merged my branch and tagged the stable. Packagist is updated as well. So simple `composer update` will not break and keep the installed version as `0.0.3`. If you don't mind, updating the entry in your `composer.json` to

```json
{
  ...
  "require-dev": {
    ...
    "mmieluch/laravel-vfs-provider": "^1.0"
  }
  ...
}
```

will install the current stable `1.0.0`.

Enjoy! And sorry about the wasted PR ;)
